#Перед виконанням даної команди потрібно щоб на віддаленій машині був публічни ключ у файлі ~/.ssh/authorized_keys
#а приватний ключ на поточній машині у файлі ~/.ssh/id_rsa (файл з цим іменем використовується за промовчанням клієнтом ssh) або в іншому файлі, (але тоді в команді потрібно вказати його імя)
# Також потрібно змінити доступи на файл $ chmod 400 ~/.ssh/id_rsa
- hosts: database_server
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
  # tasks file for catalogue-run


  
- name: Create a network
  docker_network:
    name: socks
  become: yes

- name: Run catalogue-db container
  docker_container:
    name: catalogue-db
    image: "vasylw/catalogue:latest"
    ports:
      - "3306:3306"
    restart_policy: always
    pull: yes
    user: root
  become: yes

- name: Run catalogue container
  docker_container:
    name: catalogue
    image: "vasylw/catalogue:latest"
    ports:
      - "8080:80"
    restart_policy: always
    networks:
      - name: socks
    etc_hosts:
        catalogue-db: "{{ db_host }}"
    pull: yes
    recreate: yes
    state: started 
    user: root
  become: yes
