- hosts: elk
    become: true
    vars:
     ansible_python_interpreter: "/usr/bin/env python3"
     database: "{{ hostvars[groups['elk'][0]]['inventory_hostname'] }}"

    tasks:
       
    - name: "Run elasticsearch container"
      docker_container:
        name: elasticsearch
        image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.1"
        purge_networks: yes
        networks:
          - name: socks
        ports:
         - "9200:9200"
        ports:
         - "9300:9300"
        etc_hosts:
         elasticsearch: "{{ db_host }}"
        restart_policy: always
        pull: yes
        recreate: yes
        state: started 
        user: root
      become: yes

    - name: "Run catalogue container"
      docker_container:
       name: catalogue
       image: "vasylw/catalogue:latest"
       purge_networks: yes
       networks:
         - name: socks
       ports:
       - "8080:80"
       restart_policy: always
       etc_hosts:
        catalogue-db: "{{ database }}"
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
  
    - name: "Run front-end container"
      docker_container:
       name: front-end
       image: "vasylw/frontend:latest"
       purge_networks: yes
       networks:
          - name: socks
       ports:
       - "80:8079"
       restart_policy: always
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
