- hosts: elk
    become: true
    vars:
     ansible_python_interpreter: "/usr/bin/env python3"
     host: "{{ hostvars[groups['elk'][0]]['inventory_hostname'] }}"

    tasks:
       
    - name: "Run elasticsearch container"
      docker_container:
        name: elasticsearch
        image: "elasticsearch"
        purge_networks: yes
        networks:
          - name: socks
        ports:
         - "9200:9200"
         - "9300:9300"
        etc_hosts:
         elasticsearch: "{{ host }}"
        restart_policy: always
        pull: yes
        recreate: yes
        state: started 
        user: root
      become: yes

    - name: "Run kibana container"
      docker_container:
       name: kibana
       image: "kibana"
       purge_networks: yes
       networks:
         - name: socks
       ports:
       - "5601:5601"
       restart_policy: always
       etc_hosts:
        elasticsearch: "{{ host }}"
        kibana: "{{ host }}"
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
  
    - name: "Run logstash container"
      docker_container:
       name: logstash
       image: "logstash"
       purge_networks: yes
       networks:
          - name: socks
       ports:
       - "9200:9200"
       restart_policy: always
       etc_hosts:
        logstash: "{{ host }}"
       volumes:
       - /home/
       files:
       - /home/logstash.conf
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
