- hosts: elk
    become: true
    vars:
     ansible_python_interpreter: "/usr/bin/env python3"
     database: "{{ hostvars[groups['elk'][0]]['elk'] }}"

    tasks:
       
    - name: "Run logstash container"
      docker_container:
        name: logstash
        image: "vasylw/appcarts:latest"
        purge_networks: yes
        networks:
          - name: socks
        ports:
         - "8081:80"
        restart_policy: always
        env:
          DB_NETWORK_IP: "{{ database }}"
        pull: yes
        recreate: yes
        state: started 
        user: root
      become: yes

    - name: "Run elasticsearch container"
      docker_container:
       name: elasticsearch
       image: "vasylw/catalogue:latest"
       purge_networks: yes
       networks:
         - name: socks
       ports:
       - "8080:80"
       restart_policy: always
       etc_hosts:
        catalogue-db: "{{ database }}"
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
  
    - name: "Run kebana container"
      docker_container:
       name: kebana
       image: "vasylw/frontend:latest"
       purge_networks: yes
       networks:
          - name: socks
       ports:
       - "80:8079"
       restart_policy: always
       pull: yes
       recreate: yes
       state: started 
       user: root
      become: yes
