- hosts: all
  become: true
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
    
      
    tasks:
      - name: Create a network
        docker_network:
         name: socks
         driver: overlay
         attachable: true
        become: yes
