- hosts: all
  become: true
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
 
  tasks:
 
  - name: Create a network with driver options
    docker_network:
     name: socks
     driver_options:
       driver: overlay
     ipam_options:
       subnet: '10.10.10.0/24'     
 
